name: CI tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6
        ports: ["6379:6379"]
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake spec:unit
      - name: Run integration tests
        env:
          REDIS_URL: "redis://localhost:6379"
        run: bundle exec rake spec:integration
